version: '3'
services:
  server:
    build: ./server
    tty: true
    volumes:
      - .:/go/src/timememo
    ports:
      - "5050:5050"
    networks:
      - my-network
  front:
    build: ./web
    tty: true
    volumes:
      - ./web:/timememo/web
      - /web/node_modules
    ports:
      - "9000:9000"
    networks:
      - my-network
  db:
    image: postgres
    # hostname: timememo
    ports:
      - "5432:5432"
    networks:
        - my-network
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: timememo
      POSTGRES_PASSWORD: timememo
  # web:
  #   build: ./web
  #   ports: 
  #     - "1250:1250"
networks:
  my-network:
    external: true